# Generated by Django 2.2.9 on 2021-03-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedirCarona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedircarona',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
