# Generated by Django 2.2.9 on 2021-03-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedirCarona', '0002_pedircarona_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedircarona',
            old_name='status',
            new_name='statusAndamento',
        ),
        migrations.AddField(
            model_name='pedircarona',
            name='statusCancelado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pedircarona',
            name='statusConcluido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
