# Generated by Django 2.2.9 on 2021-03-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedirCarona', '0003_auto_20210313_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedircarona',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='total'),
        ),
    ]
