# Generated by Django 2.2.9 on 2021-03-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PedirCarona', '0004_pedircarona_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedircarona',
            old_name='Usuario',
            new_name='usuario',
        ),
    ]
