# Generated by Django 2.2.9 on 2021-03-07 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
                ('nrTelCelular', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='user')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='pedirCarona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPedCarona', models.DateField(blank=True, null=True)),
                ('quantidadeVagas', models.IntegerField(verbose_name='quantidade de vagas')),
                ('destino', models.CharField(max_length=255)),
                ('partida', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedirCarona', to='usuario.usuario')),
            ],
            options={
                'db_table': 'pedirCarona',
            },
        ),
        migrations.CreateModel(
            name='oferecerCarona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataOfCarona', models.DateField(blank=True, null=True)),
                ('destino', models.CharField(blank=True, max_length=255, null=True)),
                ('partida', models.CharField(blank=True, max_length=255, null=True)),
                ('marcarCarona', models.BooleanField(default=True)),
                ('quantidadeVagas', models.IntegerField(blank=True, null=True, verbose_name='quantidade de vagas')),
                ('valorCarona', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='valor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferecerCarona', to='usuario.usuario')),
            ],
            options={
                'db_table': 'oferecerCarona',
            },
        ),
    ]
