# Generated by Django 2.2.9 on 2021-03-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferecercarona',
            name='marcarCarona',
        ),
    ]
