# Generated by Django 2.2.9 on 2021-03-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_oferecercarona_marcarcarona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedircarona',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='oferecerCarona',
        ),
        migrations.DeleteModel(
            name='pedirCarona',
        ),
    ]
