# Generated by Django 2.2.9 on 2021-03-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carona',
            old_name='oferecerCarona',
            new_name='oferecer_carona',
        ),
    ]
