# Generated by Django 2.2.9 on 2021-03-13 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0003_auto_20210310_1638'),
        ('PedirCarona', '0002_pedircarona_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('mensagem', models.CharField(max_length=255)),
                ('PedidoSolicidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedirCarona', to='PedirCarona.pedirCarona')),
                ('UsuarioEnvia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_envia', to='usuario.usuario')),
                ('UsuarioRecebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_recebe', to='usuario.usuario')),
            ],
            options={
                'db_table': 'notificacao',
            },
        ),
    ]
