# Generated by Django 2.2.9 on 2021-03-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='PedidoSolicidato',
            new_name='pedido_solicitado_id',
        ),
        migrations.RenameField(
            model_name='notificacao',
            old_name='UsuarioEnvia',
            new_name='usuario_envia_id',
        ),
        migrations.RenameField(
            model_name='notificacao',
            old_name='UsuarioRecebe',
            new_name='usuario_recebe_id',
        ),
    ]
