# Generated by Django 2.2.9 on 2021-03-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0003_auto_20210310_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='oferecerCarona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataOfCarona', models.DateField(blank=True, null=True)),
                ('quantidadeVagas', models.IntegerField(blank=True, null=True, verbose_name='quantidade de vagas')),
                ('valorCarona', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='valor')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='usuario.usuario')),
            ],
            options={
                'db_table': 'oferecerCarona',
            },
        ),
    ]
