# Generated by Django 2.2.9 on 2021-03-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OferecerCarona', '0003_auto_20210315_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferecercarona',
            old_name='valorTotal',
            new_name='valor_total',
        ),
    ]
